name: javarisk # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Java version of Risk
description: |
  Java version of Risk

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  javarisk_icon.png
title: Java Risk

apps:
  javarisk:
    command: startjavarisk
parts:
  javarisk:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      javarisk: build/
      javarisk.1: man/man1/

architectures:
  - build-on: amd64

